# Generated by Django 4.0.5 on 2022-06-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltime', models.CharField(max_length=40)),
                ('parttime', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='zuridashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('studentId', models.CharField(max_length=40)),
            ],
        ),
    ]
